Vagrant.configure("2") do |config|
    config.vm.box = "geerlingguy/centos7"
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "docker.yaml"
      ansible.inventory_path = "hosts2"
      ansible.limit = "all"
      ansible.sudo = true
    end
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "redis.yaml"
      ansible.inventory_path = "inventory"
      ansible.limit = "all"
      ansible.extra_vars = {
        redis_port: "6379"
      }
    end
    # config.vm.provision "ansible" do |ansible|
    #   ansible.playbook = "mysql-db-playbook.yaml"
    #   ansible.inventory_path = "hosts"
    #   ansible.limit = "all"
    #   ansible.sudo = true
    # end
 
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "git.yaml"
      ansible.inventory_path = "hosts2"
      ansible.limit = "all"
      ansible.sudo = true
    end
  end